spring:
  application:
    name: keycloak-auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/keycloakUserTest?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}

server:
  port: 6700
  servlet:
    context-path: /auth

app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: mBFKCtZwfD5fRATQD2WbVDej1TSsYZtX
    realm: spring
    serverUrl: http://localhost:9082